module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: ['**/*.{ts,js}', '!**/*.spec.{ts,js}', '!main.ts'],
  coverageReporters: ['text', 'lcov', 'json'],
  coverageDirectory: '../coverage',
  coverageThreshold: {
    global: {
      branches: 50,
      functions: 50,
      lines: 50,
      statements: 50,
    },
  },
  testEnvironment: 'node',
  moduleNameMapper: {
    '^@data/(.*)$': '<rootDir>/../data/$1',
    '^@auth/(.*)$': '<rootDir>/auth/$1',
    '^@users/(.*)$': '<rootDir>/users/$1',
    '^@common/(.*)$': '<rootDir>/common/$1',
    '^@app/(.*)$': '<rootDir>/app/$1',
    '^@config/(.*)$': '<rootDir>/config/$1',
    '^@mp/(.*)$': '<rootDir>/mp/$1',
    '^@shop/(.*)$': '<rootDir>/shop/$1',
    '^@item/(.*)$': '<rootDir>/item/$1',
    '^@order/(.*)$': '<rootDir>/order/$1',
    '^@payment-account/(.*)$': '<rootDir>/payment-account/$1',
    '^@/(.*)$': '<rootDir>/$1',
    '^@root/(.*)$': '<rootDir>/../$1',
  },
};
