-- AlterTable
ALTER TABLE `Order` ADD COLUMN `paymentId` VARCHAR(191) NULL,
    MODIFY `status` ENUM('PENDING', 'PAID', 'PREPARING', 'READY', 'SENT', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'PENDING';
